/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Canvas: typeof import('./src/components/Editor/Canvas.vue')['default']
    ChartRenderer: typeof import('./src/components/Render/widgets/ChartRenderer.vue')['default']
    ComponentPanel: typeof import('./src/components/Editor/ComponentPanel.vue')['default']
    DataBindingDialog: typeof import('./src/components/Editor/DataBindingDialog.vue')['default']
    DataSourcePanel: typeof import('./src/components/Editor/DataSourcePanel.vue')['default']
    DebugPanel: typeof import('./src/components/Editor/DebugPanel.vue')['default']
    DynamicRenderer: typeof import('./src/components/Render/DynamicRenderer.vue')['default']
    EditorComponentWrapper: typeof import('./src/components/Editor/EditorComponentWrapper.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTag: typeof import('element-plus/es')['ElTag']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PageRenderer: typeof import('./src/components/Render/PageRenderer.vue')['default']
    PreviewRenderer: typeof import('./src/components/Render/PreviewRenderer.vue')['default']
    PropertyPanel: typeof import('./src/components/Editor/PropertyPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toolbar: typeof import('./src/components/Editor/Toolbar.vue')['default']
  }
}

// For TSX support
declare global {
  const Canvas: typeof import('./src/components/Editor/Canvas.vue')['default']
  const ChartRenderer: typeof import('./src/components/Render/widgets/ChartRenderer.vue')['default']
  const ComponentPanel: typeof import('./src/components/Editor/ComponentPanel.vue')['default']
  const DataBindingDialog: typeof import('./src/components/Editor/DataBindingDialog.vue')['default']
  const DataSourcePanel: typeof import('./src/components/Editor/DataSourcePanel.vue')['default']
  const DebugPanel: typeof import('./src/components/Editor/DebugPanel.vue')['default']
  const DynamicRenderer: typeof import('./src/components/Render/DynamicRenderer.vue')['default']
  const EditorComponentWrapper: typeof import('./src/components/Editor/EditorComponentWrapper.vue')['default']
  const ElAlert: typeof import('element-plus/es')['ElAlert']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const ElTag: typeof import('element-plus/es')['ElTag']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const PageRenderer: typeof import('./src/components/Render/PageRenderer.vue')['default']
  const PreviewRenderer: typeof import('./src/components/Render/PreviewRenderer.vue')['default']
  const PropertyPanel: typeof import('./src/components/Editor/PropertyPanel.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Toolbar: typeof import('./src/components/Editor/Toolbar.vue')['default']
}